# Generated by Django 2.2 on 2019-12-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
