# Generated by Django 2.2 on 2019-12-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
